---
- name: libselinux-pythonとEPELリポジトリのインストール
  yum:
    name: "{{item}}"
    state: present
  with_items:
    - libselinux-python
    - epel-release

- name: Nginxのインストール
  yum:
    name: nginx
    state: present

- name: Nginxの起動と自動起動設定
  service:
    name: nginx
    state: started
    enabled: true
