---
- name: CentOS7上にWordPressをセットアップ
  hosts: all
  become: true
  roles:
    - name: common
      tags:
        - common
    - name: mariadb
      tags:
        - mariadb
    - name: php-fpm
      tags:
        - php-fpm
    - name: nginx
      tags:
        - nginx
    - name: wordpress
      tags:
        - wordpress      
